export interface Pokemon {
  id: number;
  name: string;
  sprite: string;
  animatedSprite?: string;
  type1: string;
  type2?: string;
}

export interface PokemonReward {
  id: string;
  pokemon: Pokemon;
  type: 'workout' | 'milestone' | 'streak';
  reason: string;
  timestamp: string;
  seen: boolean;
}

export const ORIGINAL_151_POKEMON = [
  { id: 1, name: 'bulbasaur', type1: 'grass', type2: 'poison' },
  { id: 2, name: 'ivysaur', type1: 'grass', type2: 'poison' },
  { id: 3, name: 'venusaur', type1: 'grass', type2: 'poison' },
  { id: 4, name: 'charmander', type1: 'fire' },
  { id: 5, name: 'charmeleon', type1: 'fire' },
  { id: 6, name: 'charizard', type1: 'fire', type2: 'flying' },
  { id: 7, name: 'squirtle', type1: 'water' },
  { id: 8, name: 'wartortle', type1: 'water' },
  { id: 9, name: 'blastoise', type1: 'water' },
  { id: 10, name: 'caterpie', type1: 'bug' },
  { id: 11, name: 'metapod', type1: 'bug' },
  { id: 12, name: 'butterfree', type1: 'bug', type2: 'flying' },
  { id: 13, name: 'weedle', type1: 'bug', type2: 'poison' },
  { id: 14, name: 'kakuna', type1: 'bug', type2: 'poison' },
  { id: 15, name: 'beedrill', type1: 'bug', type2: 'poison' },
  { id: 16, name: 'pidgey', type1: 'normal', type2: 'flying' },
  { id: 17, name: 'pidgeotto', type1: 'normal', type2: 'flying' },
  { id: 18, name: 'pidgeot', type1: 'normal', type2: 'flying' },
  { id: 19, name: 'rattata', type1: 'normal' },
  { id: 20, name: 'raticate', type1: 'normal' },
  { id: 21, name: 'spearow', type1: 'normal', type2: 'flying' },
  { id: 22, name: 'fearow', type1: 'normal', type2: 'flying' },
  { id: 23, name: 'ekans', type1: 'poison' },
  { id: 24, name: 'arbok', type1: 'poison' },
  { id: 25, name: 'pikachu', type1: 'electric' },
  { id: 26, name: 'raichu', type1: 'electric' },
  { id: 27, name: 'sandshrew', type1: 'ground' },
  { id: 28, name: 'sandslash', type1: 'ground' },
  { id: 29, name: 'nidoran-f', type1: 'poison' },
  { id: 30, name: 'nidorina', type1: 'poison' },
  { id: 31, name: 'nidoqueen', type1: 'poison', type2: 'ground' },
  { id: 32, name: 'nidoran-m', type1: 'poison' },
  { id: 33, name: 'nidorino', type1: 'poison' },
  { id: 34, name: 'nidoking', type1: 'poison', type2: 'ground' },
  { id: 35, name: 'clefairy', type1: 'fairy' },
  { id: 36, name: 'clefable', type1: 'fairy' },
  { id: 37, name: 'vulpix', type1: 'fire' },
  { id: 38, name: 'ninetales', type1: 'fire' },
  { id: 39, name: 'jigglypuff', type1: 'normal', type2: 'fairy' },
  { id: 40, name: 'wigglytuff', type1: 'normal', type2: 'fairy' },
  { id: 41, name: 'zubat', type1: 'poison', type2: 'flying' },
  { id: 42, name: 'golbat', type1: 'poison', type2: 'flying' },
  { id: 43, name: 'oddish', type1: 'grass', type2: 'poison' },
  { id: 44, name: 'gloom', type1: 'grass', type2: 'poison' },
  { id: 45, name: 'vileplume', type1: 'grass', type2: 'poison' },
  { id: 46, name: 'paras', type1: 'bug', type2: 'grass' },
  { id: 47, name: 'parasect', type1: 'bug', type2: 'grass' },
  { id: 48, name: 'venonat', type1: 'bug', type2: 'poison' },
  { id: 49, name: 'venomoth', type1: 'bug', type2: 'poison' },
  { id: 50, name: 'diglett', type1: 'ground' },
  { id: 51, name: 'dugtrio', type1: 'ground' },
  { id: 52, name: 'meowth', type1: 'normal' },
  { id: 53, name: 'persian', type1: 'normal' },
  { id: 54, name: 'psyduck', type1: 'water' },
  { id: 55, name: 'golduck', type1: 'water' },
  { id: 56, name: 'mankey', type1: 'fighting' },
  { id: 57, name: 'primeape', type1: 'fighting' },
  { id: 58, name: 'growlithe', type1: 'fire' },
  { id: 59, name: 'arcanine', type1: 'fire' },
  { id: 60, name: 'poliwag', type1: 'water' },
  { id: 61, name: 'poliwhirl', type1: 'water' },
  { id: 62, name: 'poliwrath', type1: 'water', type2: 'fighting' },
  { id: 63, name: 'abra', type1: 'psychic' },
  { id: 64, name: 'kadabra', type1: 'psychic' },
  { id: 65, name: 'alakazam', type1: 'psychic' },
  { id: 66, name: 'machop', type1: 'fighting' },
  { id: 67, name: 'machoke', type1: 'fighting' },
  { id: 68, name: 'machamp', type1: 'fighting' },
  { id: 69, name: 'bellsprout', type1: 'grass', type2: 'poison' },
  { id: 70, name: 'weepinbell', type1: 'grass', type2: 'poison' },
  { id: 71, name: 'victreebel', type1: 'grass', type2: 'poison' },
  { id: 72, name: 'tentacool', type1: 'water', type2: 'poison' },
  { id: 73, name: 'tentacruel', type1: 'water', type2: 'poison' },
  { id: 74, name: 'geodude', type1: 'rock', type2: 'ground' },
  { id: 75, name: 'graveler', type1: 'rock', type2: 'ground' },
  { id: 76, name: 'golem', type1: 'rock', type2: 'ground' },
  { id: 77, name: 'ponyta', type1: 'fire' },
  { id: 78, name: 'rapidash', type1: 'fire' },
  { id: 79, name: 'slowpoke', type1: 'water', type2: 'psychic' },
  { id: 80, name: 'slowbro', type1: 'water', type2: 'psychic' },
  { id: 81, name: 'magnemite', type1: 'electric', type2: 'steel' },
  { id: 82, name: 'magneton', type1: 'electric', type2: 'steel' },
  { id: 83, name: 'farfetchd', type1: 'normal', type2: 'flying' },
  { id: 84, name: 'doduo', type1: 'normal', type2: 'flying' },
  { id: 85, name: 'dodrio', type1: 'normal', type2: 'flying' },
  { id: 86, name: 'seel', type1: 'water' },
  { id: 87, name: 'dewgong', type1: 'water', type2: 'ice' },
  { id: 88, name: 'grimer', type1: 'poison' },
  { id: 89, name: 'muk', type1: 'poison' },
  { id: 90, name: 'shellder', type1: 'water' },
  { id: 91, name: 'cloyster', type1: 'water', type2: 'ice' },
  { id: 92, name: 'gastly', type1: 'ghost', type2: 'poison' },
  { id: 93, name: 'haunter', type1: 'ghost', type2: 'poison' },
  { id: 94, name: 'gengar', type1: 'ghost', type2: 'poison' },
  { id: 95, name: 'onix', type1: 'rock', type2: 'ground' },
  { id: 96, name: 'drowzee', type1: 'psychic' },
  { id: 97, name: 'hypno', type1: 'psychic' },
  { id: 98, name: 'krabby', type1: 'water' },
  { id: 99, name: 'kingler', type1: 'water' },
  { id: 100, name: 'voltorb', type1: 'electric' },
  { id: 101, name: 'electrode', type1: 'electric' },
  { id: 102, name: 'exeggcute', type1: 'grass', type2: 'psychic' },
  { id: 103, name: 'exeggutor', type1: 'grass', type2: 'psychic' },
  { id: 104, name: 'cubone', type1: 'ground' },
  { id: 105, name: 'marowak', type1: 'ground' },
  { id: 106, name: 'hitmonlee', type1: 'fighting' },
  { id: 107, name: 'hitmonchan', type1: 'fighting' },
  { id: 108, name: 'lickitung', type1: 'normal' },
  { id: 109, name: 'koffing', type1: 'poison' },
  { id: 110, name: 'weezing', type1: 'poison' },
  { id: 111, name: 'rhyhorn', type1: 'ground', type2: 'rock' },
  { id: 112, name: 'rhydon', type1: 'ground', type2: 'rock' },
  { id: 113, name: 'chansey', type1: 'normal' },
  { id: 114, name: 'tangela', type1: 'grass' },
  { id: 115, name: 'kangaskhan', type1: 'normal' },
  { id: 116, name: 'horsea', type1: 'water' },
  { id: 117, name: 'seadra', type1: 'water' },
  { id: 118, name: 'goldeen', type1: 'water' },
  { id: 119, name: 'seaking', type1: 'water' },
  { id: 120, name: 'staryu', type1: 'water' },
  { id: 121, name: 'starmie', type1: 'water', type2: 'psychic' },
  { id: 122, name: 'mr-mime', type1: 'psychic', type2: 'fairy' },
  { id: 123, name: 'scyther', type1: 'bug', type2: 'flying' },
  { id: 124, name: 'jynx', type1: 'ice', type2: 'psychic' },
  { id: 125, name: 'electabuzz', type1: 'electric' },
  { id: 126, name: 'magmar', type1: 'fire' },
  { id: 127, name: 'pinsir', type1: 'bug' },
  { id: 128, name: 'tauros', type1: 'normal' },
  { id: 129, name: 'magikarp', type1: 'water' },
  { id: 130, name: 'gyarados', type1: 'water', type2: 'flying' },
  { id: 131, name: 'lapras', type1: 'water', type2: 'ice' },
  { id: 132, name: 'ditto', type1: 'normal' },
  { id: 133, name: 'eevee', type1: 'normal' },
  { id: 134, name: 'vaporeon', type1: 'water' },
  { id: 135, name: 'jolteon', type1: 'electric' },
  { id: 136, name: 'flareon', type1: 'fire' },
  { id: 137, name: 'porygon', type1: 'normal' },
  { id: 138, name: 'omanyte', type1: 'rock', type2: 'water' },
  { id: 139, name: 'omastar', type1: 'rock', type2: 'water' },
  { id: 140, name: 'kabuto', type1: 'rock', type2: 'water' },
  { id: 141, name: 'kabutops', type1: 'rock', type2: 'water' },
  { id: 142, name: 'aerodactyl', type1: 'rock', type2: 'flying' },
  { id: 143, name: 'snorlax', type1: 'normal' },
  { id: 144, name: 'articuno', type1: 'ice', type2: 'flying' },
  { id: 145, name: 'zapdos', type1: 'electric', type2: 'flying' },
  { id: 146, name: 'moltres', type1: 'fire', type2: 'flying' },
  { id: 147, name: 'dratini', type1: 'dragon' },
  { id: 148, name: 'dragonair', type1: 'dragon' },
  { id: 149, name: 'dragonite', type1: 'dragon', type2: 'flying' },
  { id: 150, name: 'mewtwo', type1: 'psychic' },
  { id: 151, name: 'mew', type1: 'psychic' }
];